source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 5.2.3', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'thin'
gem 'bcrypt'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner'
end

group :development do
  gem 'sqlite3', '~> 1.3.6'
  gem 'pry'
  gem 'tux'
  gem 'shotgun'
end